##############
# Conditions #
##############

# Branch
.trigger_main: &trigger_main
  if: $CI_COMMIT_BRANCH == 'main'

############
# Workflow #
############

# 決定是否要執行pipeline
workflow:
  rules:
    - <<: *trigger_main
    # 其他情況都不觸發CI/CD
    - when: never

##########
# Stages #
##########

stages:
  - coverage

############
# coverage #
############

.coverage_template: &coverage_configuration
  image: node:latest
  stage: coverage
  script:
    - npm i -g istanbul-combine
    - istanbul-combine -d coverage -p summary ./coverage/coverage-final.json
  coverage:  /^Lines\s*:\s*([^%]+)/
  artifacts:  
    when: always
    paths:
      - coverage/

coverage:originmain:
  <<: *coverage_configuration
  rules:
    - <<: *trigger_main
  tags:
    - shared
