##############
# Conditions #
##############

# Branch
.trigger_main: &trigger_main
  if: $CI_COMMIT_BRANCH == 'main'

############
# Workflow #
############

# 決定是否要執行pipeline
workflow:
  rules:
    - <<: *trigger_main
    # 其他情況都不觸發CI/CD
    - when: never

##########
# Stages #
##########

stages:
  - coverage

############
# coverage #
############

.coverage_template: &coverage_configuration
  image: node:latest
  stage: coverage
  script:
    - npm i -g istanbul-combine
    - istanbul-combine -d coverage -p summary ./coverage/coverage-final.json
    # istanbul-combine -d coverage -p summary -r lcov -r html coverage/coverage-a.json coverage/coverage-b.json /coverage/*.json
    # - istanbul report --dir coverage --include coverage/**/coverage-final.json lcov
  # coverage: /[0-9]+.[0-9]+%.*\n.*>Lines/
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  # coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:  
    when: always
    paths:
      - coverage/
    # reports:
    #   junit: ./coverage/lcov-report/index.html

coverage:originmain:
  <<: *coverage_configuration
  rules:
    - <<: *trigger_main
  tags:
    - shared
