##############
# Conditions #
##############

# Branch
.trigger_main: &trigger_main
  if: $CI_COMMIT_BRANCH == 'main'

############
# Workflow #
############

# 決定是否要執行pipeline
workflow:
  rules:
    - <<: *trigger_main
    # 其他情況都不觸發CI/CD
    - when: never

##########
# Stages #
##########

stages:
  - coverage

############
# coverage #
############

.coverage_template: &coverage_configuration
  image: node:latest
  stage: coverage
  script:
    - npm test
    - pwd
    - cat ./coverage/lcov-report/index.html
  # coverage: /[0-9]+.[0-9]+%.*\n.*>Lines/
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - ./coverage/lcov.info

coverage:originmain:
  <<: *coverage_configuration
  rules:
    - <<: *trigger_main
  tags:
    - shared