##############
# Conditions #
##############

# Branch
.trigger_main: &trigger_main
  if: $CI_COMMIT_BRANCH == 'main'

############
# Workflow #
############

# 決定是否要執行pipeline
workflow:
  rules:
    - <<: *trigger_main
    # 其他情況都不觸發CI/CD
    - when: never

##########
# Stages #
##########

stages:
  - coverage

############
# coverage #
############

.coverage_template: &coverage_configuration
  image: node:6.9.5-alpine
  stage: coverage
  script:
    - pwd
    - cat ./coverage/lcov-report/index.html
  coverage: /[0-9]+.[0-9]+%.*\n.*>Lines/
  artifacts:
    reports:
      coverage_report:
        coverage_format: lcov
        path: ./coverage/lcov-report

coverage:originmain:
  <<: *coverage_configuration
  rules:
    - <<: *trigger_main
  tags:
    - shared